<?php

namespace HB\BlogBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * UserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserRepository extends EntityRepository
{
  public function getSelectList()
  {
    $qb = $this->createQueryBuilder('u')
                ->orderBy('u.datecre', 'DESC');
    // Et on retourne simplement le QueryBuilder, et non la Query, attention
    return $qb;
  }
}
